import Image from "next/image";
import Link from "next/link";
import { getTranslations } from "next-intl/server";
import { BookingForm } from "@/components/booking/booking-form";
import { getSpecialty } from "@/lib/catalog/data";
import { getClinic } from "@/lib/clinics/data";
import { media } from "@/lib/media/registry";

export default async function LeadPage({ params, searchParams }: { params: Promise<{ locale: string }>; searchParams: Promise<{ specialty?: string; clinic?: string }> }) { const { locale } = await params; const { specialty: specialtySlug, clinic: clinicSlug } = await searchParams; const t = await getTranslations("Lead"); const specialty = specialtySlug ? getSpecialty(specialtySlug) : undefined; const clinic = clinicSlug ? getClinic(clinicSlug) : undefined; const english = locale === "en"; return <main><section className="bg-deep text-white"><div className="container-shell grid gap-10 py-16 md:grid-cols-[.8fr_1.2fr] md:items-end md:py-24"><div><Link className="inline-flex min-h-11 items-center text-sm font-semibold text-white/70 hover:text-white" href={`/${locale}`}>← {t("backHome")}</Link><p className="eyebrow eyebrow-on-dark mt-14">{t("eyebrow")}</p><h1 className="mt-4 max-w-3xl font-display text-6xl font-semibold leading-[.95]">{t("title")}</h1></div><p className="max-w-xl text-lg leading-8 text-white/70">{t("description")}</p></div></section><section className="container-shell grid gap-10 py-16 md:grid-cols-[.7fr_1.3fr] md:py-24 md:items-start"><div className="reveal"><div className="image-frame relative min-h-[20rem]"><Image src={media.trust.documents.desktop} alt={media.trust.documents.alt[english ? "en" : "es"]} fill sizes="(max-width: 768px) 100vw, 40vw" className="object-cover" /></div>{specialty && <div className="mt-6 rounded-[1.5rem] bg-champagne-light p-6"><p className="eyebrow">{t("selectedSpecialty")}</p><p className="mt-2 font-display text-3xl font-semibold text-sapphire">{specialty.name[locale as "es" | "en"]}</p></div>}{clinic && <div className="mt-4 rounded-[1.5rem] bg-champagne-light p-6"><p className="eyebrow">{english ? "Selected clinic" : "Clínica seleccionada"}</p><p className="mt-2 font-display text-3xl font-semibold text-sapphire">{clinic.name}</p></div>}<div className="mt-6 rounded-[1.5rem] border border-border bg-surface p-6 text-sm leading-6 text-muted">{t("privacyNote")}</div></div><BookingForm defaultSpecialty={specialty?.slug} defaultClinic={clinic?.slug} /></section></main>; }
