"use client";

import Image from "next/image";
import { useState } from "react";
import { CheckCircle2, ClipboardList, FileText, MessageCircle, Plane, ShieldCheck, Stethoscope } from "lucide-react";
import { media } from "@/lib/media/registry";

const steps = {
  es: [["Primera conversación", "Un asesor entiende qué área quieres valorar y te explica cómo solicitar contacto, sin pedirte información clínica sensible.", ClipboardList, media.trust.call.desktop], ["Información general", "Te ayudamos a formular preguntas para hablar con el centro o proveedor independiente.", MessageCircle, media.partners.international.desktop], ["Contacto directo", "Si procede, facilitamos el contacto con el proveedor correspondiente. La contratación se realiza directamente con quien presta el servicio.", FileText, media.trust.documents.desktop], ["Servicios independientes", "Vuelo, alojamiento y transporte no son servicios de Aura: sus condiciones las confirma y contrata cada proveedor.", Plane, media.hotel.exterior.desktop], ["Valoración sanitaria", "El equipo sanitario decide la idoneidad, el plan, los riesgos y el seguimiento clínico.", Stethoscope, media.partners.international.desktop], ["Decisión informada", "Aura no diagnostica, no garantiza resultados y no responde de la asistencia prestada por terceros.", ShieldCheck, media.partners.team.desktop]],
  en: [["First conversation", "An advisor understands which area you want to explore and explains how to request contact without asking for sensitive clinical information.", ClipboardList, media.trust.call.desktop], ["General information", "We help you prepare questions for the independent centre or provider.", MessageCircle, media.partners.international.desktop], ["Direct contact", "Where appropriate, we facilitate contact with the relevant provider. Contracting takes place directly with the service provider.", FileText, media.trust.documents.desktop], ["Independent services", "Flights, accommodation and transport are not Aura services: each provider confirms and contracts its own terms.", Plane, media.hotel.exterior.desktop], ["Healthcare assessment", "The healthcare team decides suitability, planning, risks and clinical follow-up.", Stethoscope, media.partners.international.desktop], ["Informed decision", "Aura does not diagnose, guarantee outcomes or provide third-party healthcare.", ShieldCheck, media.partners.team.desktop]],
} as const;

export function TravelTimeline({ locale }: { locale: string }) {
  const english = locale === "en";
  const items = steps[english ? "en" : "es"];
  const [active, setActive] = useState(0);
  const ActiveIcon = items[active][2];
  return <div className="mt-10 grid gap-7 lg:grid-cols-[.7fr_1.3fr] lg:items-stretch"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-1">{items.map(([title, , Icon], index) => <button key={title} type="button" onClick={() => setActive(index)} className={`group flex min-h-16 items-center gap-4 rounded-2xl border p-4 text-left transition ${active === index ? "border-sapphire bg-sapphire text-white shadow-soft" : "border-border bg-canvas text-sapphire hover:bg-white"}`} aria-pressed={active === index}><span className={`grid size-10 shrink-0 place-items-center rounded-full ${active === index ? "bg-white/15" : "bg-champagne-light"}`}><Icon size={18} aria-hidden="true" /></span><span><span className="block text-xs font-bold uppercase tracking-[.16em] opacity-70">0{index + 1}</span><span className="mt-1 block font-semibold">{title}</span></span></button>)}</div><article className="relative min-h-[24rem] overflow-hidden rounded-[2rem] bg-deep text-white shadow-soft" aria-live="polite"><Image src={items[active][3]} alt="" fill sizes="(max-width: 1024px) 100vw, 60vw" className="object-cover opacity-35 transition duration-slow" /><div className="absolute inset-0 bg-gradient-to-t from-deep via-deep/55 to-deep/20" /><div className="relative flex h-full min-h-[24rem] flex-col justify-end p-8 md:p-10"><div className="grid size-14 place-items-center rounded-full bg-white/10"><ActiveIcon size={26} aria-hidden="true" /></div><p className="mt-8 text-sm font-bold uppercase tracking-[.18em] text-champagne-light">0{active + 1} / 0{items.length}</p><h3 className="mt-3 font-display text-4xl font-semibold">{items[active][0]}</h3><p className="mt-5 max-w-xl text-lg leading-8 text-white/75">{items[active][1]}</p><div className="mt-8 flex items-center gap-2 text-sm text-white/60"><CheckCircle2 size={16} aria-hidden="true" />{english ? "Clear information at every stage" : "Información clara en cada etapa"}</div></div></article></div>;
}
