"use client";

import Image from "next/image";
import { useState } from "react";
import { BedDouble, Building2, CheckCircle2, ClipboardList, Plane, Stethoscope, Truck } from "lucide-react";
import { media } from "@/lib/media/registry";

const steps = {
  es: [["Primera conversación", "Un asesor entiende lo que quieres valorar y te explica qué información necesitas para empezar.", ClipboardList, media.trust.call.desktop], ["Valoración y opciones", "Facilitamos la conversación con los centros disponibles; el equipo sanitario determina la indicación.", Stethoscope, media.partners.international.desktop], ["Preparación del vuelo", "Coordinamos fechas, documentación, equipaje y horarios alrededor de la agenda confirmada.", Plane, "/images/journey/journey-flight.webp"], ["Llegada y traslado", "Coordinamos la recogida en el aeropuerto y el traslado al hotel o al centro según el itinerario confirmado.", Truck, media.transport.airport.desktop], ["Hotel y estancia", "Coordinamos el alojamiento seleccionado y revisamos contigo sus condiciones, ubicación y fechas.", BedDouble, media.hotel.room.desktop], ["Clínica y seguimiento", "El centro realiza la atención sanitaria y facilita las pautas de revisión. Aura acompaña la parte práctica del viaje.", Building2, "/images/journey/journey-hospital.webp"]],
  en: [["First conversation", "An advisor understands what you want to explore and explains what information you need to begin.", ClipboardList, media.trust.call.desktop], ["Assessment and options", "We facilitate a conversation with available centres; the healthcare team decides suitability.", Stethoscope, media.partners.international.desktop], ["Flight preparation", "We coordinate dates, documents, luggage and timings around the confirmed schedule.", Plane, "/images/journey/journey-flight.webp"], ["Arrival and transfer", "We coordinate airport reception and transport to the hotel or centre according to the confirmed itinerary.", Truck, media.transport.airport.desktop], ["Hotel and stay", "We coordinate the selected accommodation and review its terms, location and dates with you.", BedDouble, media.hotel.room.desktop], ["Clinic and follow-up", "The centre provides healthcare and shares review guidance. Aura supports the practical side of the journey.", Building2, "/images/journey/journey-hospital.webp"]],
} as const;

export function TravelTimeline({ locale }: { locale: string }) { const english = locale === "en"; const items = steps[english ? "en" : "es"]; const [active, setActive] = useState(0); const ActiveIcon = items[active][2]; return <div className="mt-10 grid gap-7 lg:grid-cols-[.7fr_1.3fr] lg:items-stretch"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-1">{items.map(([title, , Icon], index) => <button key={title} type="button" onClick={() => setActive(index)} className={`group flex min-h-16 items-center gap-4 rounded-2xl border p-4 text-left transition ${active === index ? "border-sapphire bg-sapphire text-white shadow-soft" : "border-border bg-canvas text-sapphire hover:bg-white"}`} aria-pressed={active === index}><span className={`grid size-10 shrink-0 place-items-center rounded-full ${active === index ? "bg-white/15" : "bg-champagne-light"}`}><Icon size={18} aria-hidden="true" /></span><span><span className="block text-xs font-bold uppercase tracking-[.16em] opacity-70">0{index + 1}</span><span className="mt-1 block font-semibold">{title}</span></span></button>)}</div><article className="relative min-h-[24rem] overflow-hidden rounded-[2rem] bg-deep text-white shadow-soft" aria-live="polite"><Image src={items[active][3]} alt="" fill sizes="(max-width: 1024px) 100vw, 60vw" className="object-cover opacity-35 transition duration-slow" /><div className="absolute inset-0 bg-gradient-to-t from-deep via-deep/55 to-deep/20" /><div className="relative flex h-full min-h-[24rem] flex-col justify-end p-8 md:p-10"><div className="grid size-14 place-items-center rounded-full bg-white/10"><ActiveIcon size={26} aria-hidden="true" /></div><p className="mt-8 text-sm font-bold uppercase tracking-[.18em] text-champagne-light">0{active + 1} / 0{items.length}</p><h3 className="mt-3 font-display text-4xl font-semibold">{items[active][0]}</h3><p className="mt-5 max-w-xl text-lg leading-8 text-white/75">{items[active][1]}</p><div className="mt-8 flex items-center gap-2 text-sm text-white/60"><CheckCircle2 size={16} aria-hidden="true" />{english ? "Clear support at every stage" : "Acompañamiento claro en cada etapa"}</div></div></article></div>; }
