export const editorialFields = [
  ["home.hero.title", "Home", "Hero", "Título principal", "textarea"],
  ["home.hero.description", "Home", "Hero", "Descripción principal", "textarea"],
  ["home.hero.primary_cta", "Home", "Hero", "CTA principal", "text"],
  ["home.journey.title", "Home", "Tu viaje", "Título del recorrido", "textarea"],
  ["home.journey.description", "Home", "Tu viaje", "Descripción del recorrido", "textarea"],
  ["specialties.intro.title", "Especialidades", "Introducción", "Título", "textarea"],
  ["specialties.intro.description", "Especialidades", "Introducción", "Descripción", "textarea"],
  ["clinics.intro.title", "Clínicas", "Introducción", "Título", "textarea"],
  ["clinics.intro.description", "Clínicas", "Introducción", "Descripción", "textarea"],
  ["journey.intro.title", "Viaje", "Introducción", "Título", "textarea"],
  ["journey.intro.description", "Viaje", "Introducción", "Descripción", "textarea"],
  ["contact.intro.title", "Contacto", "Introducción", "Título", "textarea"],
  ["contact.intro.description", "Contacto", "Introducción", "Descripción", "textarea"],
] as const;
