"use client";

import { FormEvent, useState } from "react";
import { Button } from "@/components/ui/button";
import { getEditorialContent, saveEditorialField, saveEditorialMedia, type EditorialField, type EditorialMedia } from "@/lib/actions/editorial-content";
import { editorialFields } from "@/lib/admin/editorial-fields";

const statuses = ["draft", "review", "verified", "published", "archived"] as const;
const inputClass = "mt-2 w-full rounded-xl border border-border bg-white px-3 py-3 text-sm";

export function EditorialPanel({ initialFields, initialMedia }: { initialFields: EditorialField[]; initialMedia: EditorialMedia[] }) {
  const [fields, setFields] = useState(initialFields); const [media, setMedia] = useState(initialMedia); const [message, setMessage] = useState("");
  async function refresh() { const result = await getEditorialContent(); if (!result.ok) { setMessage(result.message); return; } setFields(result.fields); setMedia(result.media); setMessage("Contenido actualizado."); }
  async function saveField(event: FormEvent<HTMLFormElement>, key: string) { event.preventDefault(); const form = new FormData(event.currentTarget); const definition = editorialFields.find((item) => item[0] === key); if (!definition) return; const current = fields.find((item) => item.content_key === key); const result = await saveEditorialField({ id: current?.id || null, contentKey: key, page: definition[1], section: definition[2], label: definition[3], fieldType: definition[4], valueEs: String(form.get("valueEs") || ""), valueEn: String(form.get("valueEn") || ""), status: String(form.get("status") || "draft"), sortOrder: editorialFields.findIndex((item) => item[0] === key) }); setMessage(result.ok ? "Campo guardado." : result.message); if (result.ok) await refresh(); }
  async function saveMedia(event: FormEvent<HTMLFormElement>, current?: EditorialMedia) { event.preventDefault(); const form = new FormData(event.currentTarget); const result = await saveEditorialMedia({ id: current?.id || null, mediaKey: String(form.get("mediaKey") || ""), page: String(form.get("page") || ""), label: String(form.get("label") || ""), path: String(form.get("path") || ""), altEs: String(form.get("altEs") || ""), altEn: String(form.get("altEn") || ""), status: String(form.get("status") || "draft"), sortOrder: Number(form.get("sortOrder") || 0) }); setMessage(result.ok ? "Imagen guardada." : result.message); if (result.ok) await refresh(); }
  return <section className="mt-10 space-y-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="eyebrow">Editor editorial</p><h2 className="mt-2 font-display text-3xl text-sapphire">Textos e imágenes del sitio</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">Edita solo campos definidos por Aura. Publicar un cambio no modifica la estructura ni las funciones del sitio.</p></div><Button tone="secondary" type="button" onClick={() => void refresh()}>Actualizar</Button></div>{message ? <p role="status" className="rounded-xl border border-info/20 bg-info/10 px-4 py-3 text-sm text-info">{message}</p> : null}<div className="grid gap-6 lg:grid-cols-2">{[...new Set(editorialFields.map((item) => item[1]))].map((page) => <section key={page} className="rounded-2xl border border-border bg-white p-5 shadow-soft"><p className="eyebrow">{page}</p><div className="mt-5 space-y-5">{editorialFields.filter((item) => item[1] === page).map(([key, , section, label, type]) => { const current = fields.find((item) => item.content_key === key); return <form key={key} onSubmit={(event) => void saveField(event, key)} className="rounded-xl border border-border bg-surface p-4"><div className="flex items-center justify-between gap-3"><label className="text-sm font-semibold text-sapphire">{label}<span className="ml-2 text-xs font-normal text-muted">{section}</span></label><span className="text-xs text-muted">{current?.status || "nuevo"}</span></div><textarea name="valueEs" rows={type === "text" ? 2 : 4} defaultValue={current?.value_es || ""} placeholder="Español" className={inputClass} /><textarea name="valueEn" rows={type === "text" ? 2 : 4} defaultValue={current?.value_en || ""} placeholder="English" className={inputClass} /><div className="mt-3 flex flex-wrap items-end justify-between gap-3"><label className="text-xs font-semibold text-muted">Estado<select name="status" defaultValue={current?.status || "draft"} className="ml-2 rounded-lg border border-border bg-white px-2 py-2 text-xs">{statuses.map((status) => <option key={status}>{status}</option>)}</select></label><Button type="submit">Guardar</Button></div></form>; })}</div></section>)}</div><section className="rounded-2xl border border-border bg-white p-5 shadow-soft"><p className="eyebrow">Recursos visuales</p><h3 className="mt-2 font-display text-3xl text-sapphire">Imágenes editables</h3><p className="mt-2 text-sm text-muted">Introduce rutas existentes del proyecto o URLs aprobadas. La subida directa a Storage se añadirá después de validar la biblioteca.</p><div className="mt-5 grid gap-5 lg:grid-cols-2">{media.map((item) => <MediaForm key={item.media_key} item={item} onSubmit={saveMedia} />)}<MediaForm onSubmit={saveMedia} /></div></section></section>;
}

function MediaForm({ item, onSubmit }: { item?: EditorialMedia; onSubmit: (event: FormEvent<HTMLFormElement>, current?: EditorialMedia) => Promise<void> }) { return <form onSubmit={(event) => void onSubmit(event, item)} className="rounded-xl border border-border bg-surface p-4"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold text-sapphire">Clave<input required name="mediaKey" defaultValue={item?.media_key || ""} className={inputClass} /></label><label className="text-sm font-semibold text-sapphire">Página<input required name="page" defaultValue={item?.page || ""} className={inputClass} /></label></div><label className="mt-3 block text-sm font-semibold text-sapphire">Etiqueta<input required name="label" defaultValue={item?.label || ""} className={inputClass} /></label><label className="mt-3 block text-sm font-semibold text-sapphire">Ruta o URL<input required name="path" defaultValue={item?.path || ""} placeholder="/images/..." className={inputClass} /></label><div className="mt-3 grid gap-3 sm:grid-cols-2"><input name="altEs" defaultValue={item?.alt_es || ""} placeholder="Alt ES" className={inputClass} /><input name="altEn" defaultValue={item?.alt_en || ""} placeholder="Alt EN" className={inputClass} /></div><div className="mt-3 flex items-end justify-between gap-3"><label className="text-xs font-semibold text-muted">Estado<select name="status" defaultValue={item?.status || "draft"} className="ml-2 rounded-lg border border-border bg-white px-2 py-2 text-xs">{statuses.map((status) => <option key={status}>{status}</option>)}</select></label><input type="hidden" name="sortOrder" value={item?.sort_order || 0} /><Button type="submit">Guardar imagen</Button></div></form>; }
