import Link from "next/link";
import { specialties } from "@/lib/catalog/data";
import { ButtonLink } from "@/components/ui/button";

export default async function SpecialtiesPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const language = locale as "es" | "en";
  const english = locale === "en";
  return <main className="container-shell py-16"><Link className="inline-flex min-h-11 items-center text-sm font-semibold text-sapphire" href={`/${locale}`}>← Aura Estética</Link><div className="reveal mt-12 max-w-3xl"><p className="eyebrow">Aura Estética</p><h1 className="mt-4 font-display text-5xl text-sapphire">{english ? "A directory of possibilities" : "Un directorio para informarte"}</h1><p className="mt-4 text-lg leading-8 text-muted">{english ? "Explore each specialty, treatment line and specific option. The right starting point is an informed conversation, not a rushed decision." : "Explora cada especialidad, línea de tratamiento y opción específica. El punto de partida es una conversación informada, no una decisión apresurada."}</p></div><div className="mt-14 divide-y divide-border border-y border-border">{specialties.map((specialty) => <section key={specialty.slug} className="grid gap-6 py-9 md:grid-cols-[.75fr_1.25fr] md:gap-12"><div><p className="eyebrow">{english ? "Specialty" : "Especialidad"}</p><h2 className="mt-2 font-display text-3xl text-sapphire"><Link href={`/${locale}/especialidades/${specialty.slug}`} className="hover:text-sapphire-dark">{specialty.name[language]}</Link></h2><p className="mt-3 text-sm leading-6 text-muted">{specialty.shortDescription[language]}</p></div><div className="grid gap-x-8 gap-y-5 sm:grid-cols-2">{specialty.services.map((service) => <div key={service.slug}><Link href={`/${locale}/especialidades/${specialty.slug}/${service.slug}`} className="font-semibold text-sapphire hover:text-sapphire-dark">{service.name[language]}</Link><p className="mt-1 text-xs leading-5 text-muted">{service.options.map((item) => item.name[language]).join(" · ")}</p></div>)}</div></section>)}</div><div className="mt-12 flex flex-wrap items-center justify-between gap-5 rounded-[1.5rem] bg-surface p-7"><div><p className="eyebrow">{english ? "The process starts before you travel" : "El proceso comienza antes de viajar"}</p><p className="mt-2 font-display text-2xl text-sapphire">{english ? "Understand the journey, from Spain to your return home." : "Conoce el viaje completo, desde España hasta tu regreso a casa."}</p></div><ButtonLink href={`/${locale}/como-funciona`}>{english ? "Start your journey" : "Empieza tu viaje"}</ButtonLink></div></main>;
}
