import Link from "next/link";
import Image from "next/image";
import { ButtonLink } from "@/components/ui/button";
import { media } from "@/lib/media/registry";

export default async function TransportPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const english = locale === "en";
  const stops = english
    ? [["Airport", "A transfer may be offered directly by the responsible provider.", "airport-pickup"], ["Hotel", "The accommodation provider confirms any connection or local transport.", "hotel-transfer"], ["Independent transfer", "Vehicle, route, hours, luggage and price belong to the responsible transport provider.", "private-luxury-transfer"]]
    : [["Aeropuerto", "El proveedor responsable puede ofrecer directamente un traslado.", "airport-pickup"], ["Hotel", "El proveedor de alojamiento confirma cualquier conexión o transporte local.", "hotel-transfer"], ["Traslado independiente", "El vehículo, la ruta, los horarios, el equipaje y el precio corresponden al proveedor de transporte.", "private-luxury-transfer"]];
  return <main className="container-shell py-16"><Link className="text-sm font-semibold text-sapphire" href={`/${locale}/como-funciona`}>← {english ? "Back to the process" : "Volver al proceso"}</Link><div className="image-frame relative mt-12 min-h-[360px] overflow-hidden"><Image src={media.transport.private.desktop} alt={english ? "Representative private transfer" : "Traslado privado representativo"} fill priority sizes="(max-width: 768px) 100vw, 1180px" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-sapphire/85 via-sapphire/10 to-transparent" /><div className="absolute bottom-8 left-8 right-8 text-white md:left-12 md:right-12"><p className="eyebrow eyebrow-on-dark">{english ? "Independent provider" : "Proveedor independiente"}</p><h1 className="mt-4 font-display text-5xl">{english ? "Transport information" : "Información de transporte"}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-white/80">{english ? "Aura does not provide or sell transfers. Any transport option is confirmed and contracted directly with the responsible provider." : "Aura no presta ni vende traslados. Cualquier opción de transporte se confirma y contrata directamente con el proveedor responsable."}</p></div></div><section className="mt-12 grid gap-5 md:grid-cols-3">{stops.map(([title, text, file]) => <article key={title} className="group overflow-hidden rounded-[1.5rem] border border-border bg-white shadow-soft"><div className="relative h-48"><Image src={`/images/transport/${file}.webp`} alt={title} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover transition duration-slow group-hover:scale-105" /></div><div className="p-7"><h2 className="font-display text-2xl text-sapphire">{title}</h2><p className="mt-3 text-sm leading-6 text-muted">{text}</p></div></article>)}</section><p className="mt-10 text-sm leading-6 text-muted">{english ? "Provider, vehicle, accessibility, luggage conditions, hours and price are not services supplied by Aura and must be confirmed in writing by the responsible provider." : "El proveedor, vehículo, accesibilidad, condiciones de equipaje, horarios y precio no son servicios prestados por Aura y deben confirmarse por escrito con el proveedor responsable."}</p><ButtonLink className="mt-8" href={`/${locale}/reservar`}>{english ? "Request general information" : "Solicitar información general"}</ButtonLink></main>;
}
